export enum EstadoSuscripcion {
  PENDIENTE_PAGO = 'PENDIENTE DE PAGO',
  PAGADO_ESPERA_INICIO = 'PAGADO CON ESPERA A LA FECHA INICIO',
  ACTIVA = 'ACTIVA',
  VENCIDA = 'VENCIDA',
  SIN_SUSCRIPCION = 'SIN SUSCRIPCION',
  PENDIENTE_RENOVAR = 'PENDIENTE RENOVAR',
}
